#ifndef POLARIZELIB_GLOBAL_H
#define POLARIZELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POLARIZELIB_LIBRARY)
#  define POLARIZELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POLARIZELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POLARIZELIB_GLOBAL_H
